# GneshaOS — top-level parameters (template / documentation copy).
#
# Copy this file to params.nix and edit. THIS FILE IS ALSO THE FALLBACK:
# flake.nix loads params.nix when present, otherwise this example, so a fresh
# clone always evaluates. Values below are the reference machine's (cf-fv1,
# user "lg") — change them to yours.
#
# Usage:
#   1. cp params.example.nix params.nix
#   2. Edit the values you care about (at minimum userName, gitUserName,
#      gitUserEmail, timeZone, latitude/longitude, keyboardLayout).
#   3. nixos-rebuild switch --flake .#<hostName>
#
# Every field below flows into the configs listed next to it. Nothing else in
# the repo needs editing for a new user — except hosts/<host>/hardware-
# configuration.nix, which is machine-generated by `nixos-generate-config`
# (disk UUIDs etc.) and is intentionally not parameterised.
{
  systemSettings = {
    # Machine hostname. Sets networking.hostName, the samba "server string",
    # and is the attr name you target with `--flake .#<hostName>`.
    #   Used by: flake.nix, hosts/<host>/default.nix
    hostName = "cf-fv1";

    # Absolute path of this flake directory on your machine.
    #   Used by: home/shell.nix (rebuild/retest/rebuild-boot/nixcheck/nixeval
    #   aliases), home/desktop/daemons.nix (als-brightness unit).
    #   Default: /etc/nixos (standard location; often a symlink to your repo).
    flakePath = "/etc/nixos";
  };

  userSettings = {
    # Your POSIX login name. Must match the user you create in
    # hosts/<host>/default.nix and your @home btrfs subvolume.
    #   Used by: flake.nix (home-manager user), home/default.nix,
    #   hosts/<host>/default.nix (samba valid/force user, docker extraGroups),
    #   home/theme.nix (colorScheme author).
    userName = "lg";

    # Git identity for `programs.git` in home/editors.nix.
    gitUserName = "lg";
    gitUserEmail = "lg@lgreve.com";

    # Absolute home directory.
    #   Used by: home/default.nix (home.homeDirectory).
    homeDirectory = "/home/lg";

    # System timezone (IANA name).
    #   Used by: hosts/<host>/default.nix (time.timeZone).
    timeZone = "Australia/Sydney";

    # Your location, decimal degrees, for wlsunset's day/night tint.
    # South/west are negative.
    #   Used by: home/desktop/sway.nix (startup wlsunset command).
    latitude = -33.87;
    longitude = 151.21;

    # Keyboard layout (xkb_layout) and option remaps (xkb_options).
    #   Used by: home/desktop/sway.nix (input "type:keyboard").
    keyboardLayout = "us";
    keyboardOptions = "ctrl:nocaps";

    # Native panel resolution in pixels. The wallpaper generator in
    # home/theme.nix sizes its SVG from these (it used to hardcode 2160x1440).
    displayWidth = 2160;
    displayHeight = 1440;

    # Sway output scaling. "2" = 200% (HiDPI), "1" = 100%. Must be a string.
    # Also the value scale.sh resets to (Mod+0 / "default").
    #   Used by: home/desktop/sway.nix, home/desktop/scripts/scale.sh.
    displayScale = "2";

    # Sway gaps (px).
    #   Used by: home/desktop/sway-extra.conf (gaps inner/outer).
    gapsInner = 5;
    gapsOuter = 5;

    # foot terminal font size (pt).
    #   Used by: home/desktop/foot.nix (font=monospace:size=).
    terminalFontSize = 11;

    # Where screenshots are saved (grimshot + mkdir -p on session start).
    #   Used by: home/desktop/sway.nix (startup).
    screenshotDir = "~/Pictures/Screenshots";

    # Anonymous image host used by the screenshot-upload bindings
    # (Print+Shift). Leave as-is to keep uploads, or point at your own
    # 0x0-compatible endpoint.
    #   Used by: home/desktop/sway-extra.conf (set $upload_pipe).
    screenshotUploadUrl = "https://x0.at/";

    # swayidle timeouts in seconds, and the brightness dim level (%).
    # Sequence: dim -> lock -> DPMS off -> suspend (battery only).
    #   Used by: home/desktop/daemons.nix (services.swayidle.timeouts).
    idleDimSec = 240;
    idleDimPercent = 10;
    idleLockSec = 300;
    idleOffSec = 600;
    idleSuspendSec = 900;

    # Backlight device name (check `brightnessctl -l`).
    #   Used by: home/desktop/waybar.nix (backlight module),
    #   home/desktop/scripts/als-brightness.sh.
    backlightDevice = "intel_backlight";

    # IIO ambient-light sensor raw path (check /sys/bus/iio/devices/ —
    # the *in_illuminance_raw* device). Used by als-brightness.sh.
    alsSensorPath = "/sys/bus/iio/devices/iio:device4/in_illuminance_raw";

    # Absolute path of your docker-compose.yml for the *arr media stack.
    #   Used by: hosts/<host>/default.nix (docker-compose-stop unit).
    arrComposePath = "/home/lg/src/arr/docker-compose.yml";
  };
}
